/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imaccess;

/**
 *
 * @author ACER
 */
public class IMAccess extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public IMAccess() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panel_rbn_body = new javax.swing.JPanel();
        panel_rbn_accounts = new javax.swing.JPanel();
        btn_rbnI_add_visitor1 = new javax.swing.JButton();
        btn_rbnI_add_stuent1 = new javax.swing.JButton();
        btn_rbnI_add_lecturer1 = new javax.swing.JButton();
        panel_rbn_Attendance = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        rbn_student = new javax.swing.JButton();
        btn_rbn_accounts = new javax.swing.JButton();
        rbn_attendance = new javax.swing.JButton();
        panel_body = new javax.swing.JPanel();
        panel_add_student = new javax.swing.JPanel();
        txt_acc_user_first_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_acc_user_last_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_acc_user_full_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_acc_student_address = new javax.swing.JTextField();
        combo_acc_user_title = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_rbn_body.setBackground(new java.awt.Color(255, 255, 255));
        panel_rbn_body.setLayout(new java.awt.CardLayout());

        panel_rbn_accounts.setBackground(new java.awt.Color(255, 255, 255));
        panel_rbn_accounts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_rbnI_add_visitor1.setText("Add Visitor");
        panel_rbn_accounts.add(btn_rbnI_add_visitor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 188, 91));

        btn_rbnI_add_stuent1.setText("Add Student");
        panel_rbn_accounts.add(btn_rbnI_add_stuent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, 191, 91));

        btn_rbnI_add_lecturer1.setText("Add Lecturer");
        btn_rbnI_add_lecturer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rbnI_add_lecturer1ActionPerformed(evt);
            }
        });
        panel_rbn_accounts.add(btn_rbnI_add_lecturer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 190, 91));

        panel_rbn_body.add(panel_rbn_accounts, "card2");

        panel_rbn_Attendance.setBackground(new java.awt.Color(255, 255, 255));
        panel_rbn_Attendance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("test");
        panel_rbn_Attendance.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 80));

        panel_rbn_body.add(panel_rbn_Attendance, "card3");

        jPanel2.add(panel_rbn_body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1010, 80));

        rbn_student.setText("Student");
        jPanel2.add(rbn_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 190, 30));

        btn_rbn_accounts.setText("Accounts");
        btn_rbn_accounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rbn_accountsActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rbn_accounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 30));

        rbn_attendance.setText("Attendance");
        rbn_attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbn_attendanceActionPerformed(evt);
            }
        });
        jPanel2.add(rbn_attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, -1));

        panel_body.setBackground(new java.awt.Color(255, 255, 255));
        panel_body.setLayout(new java.awt.CardLayout());

        panel_add_student.setBackground(new java.awt.Color(255, 255, 255));
        panel_add_student.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_add_student.add(txt_acc_user_first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 95, 211, 37));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("First Name");
        panel_add_student.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 67, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Last Name");
        panel_add_student.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 67, -1, -1));
        panel_add_student.add(txt_acc_user_last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 95, 221, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name with Initials");
        panel_add_student.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 138, -1, -1));
        panel_add_student.add(txt_acc_user_full_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 166, 510, 37));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Name with Initials");
        panel_add_student.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 217, -1, -1));
        panel_add_student.add(txt_acc_student_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 245, 510, 94));

        combo_acc_user_title.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr", "Miss", "Mrs", "Ven" }));
        combo_acc_user_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_acc_user_titleActionPerformed(evt);
            }
        });
        panel_add_student.add(combo_acc_user_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 95, -1, 37));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Title");
        panel_add_student.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 67, -1, -1));

        panel_body.add(panel_add_student, "card2");

        getContentPane().add(panel_body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1010, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_rbnI_add_lecturer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rbnI_add_lecturer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_rbnI_add_lecturer1ActionPerformed

    private void btn_rbn_accountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rbn_accountsActionPerformed
        System.out.println("action");
        
        panel_rbn_body.removeAll();
        panel_rbn_body.repaint();
        panel_rbn_body.revalidate();
        
        panel_rbn_body.add(panel_rbn_accounts);
        panel_rbn_body.repaint();
        panel_rbn_body.revalidate();
    }//GEN-LAST:event_btn_rbn_accountsActionPerformed

    private void rbn_attendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbn_attendanceActionPerformed
        // TODO add your handling code here:
        System.out.println("accounts");
        panel_rbn_body.removeAll();
        panel_rbn_body.repaint();
        panel_rbn_body.revalidate();
        
        panel_rbn_body.add(panel_rbn_Attendance);
        panel_rbn_body.repaint();
        panel_rbn_body.revalidate();
    }//GEN-LAST:event_rbn_attendanceActionPerformed

    private void combo_acc_user_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_acc_user_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_acc_user_titleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IMAccess().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_rbnI_add_lecturer1;
    private javax.swing.JButton btn_rbnI_add_stuent1;
    private javax.swing.JButton btn_rbnI_add_visitor1;
    private javax.swing.JButton btn_rbn_accounts;
    private javax.swing.JComboBox<String> combo_acc_user_title;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_add_student;
    private javax.swing.JPanel panel_body;
    private javax.swing.JPanel panel_rbn_Attendance;
    private javax.swing.JPanel panel_rbn_accounts;
    private javax.swing.JPanel panel_rbn_body;
    private javax.swing.JButton rbn_attendance;
    private javax.swing.JButton rbn_student;
    private javax.swing.JTextField txt_acc_student_address;
    private javax.swing.JTextField txt_acc_user_first_name;
    private javax.swing.JTextField txt_acc_user_full_name;
    private javax.swing.JTextField txt_acc_user_last_name;
    // End of variables declaration//GEN-END:variables
}
