/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imaccess;

import Queries.LectureQueries;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class StdDetails extends javax.swing.JFrame {

    /**
     * Creates new form StdDetails
     */
    public StdDetails(ResultSet stdDet) {
        initComponents();
        
        ResultSet stdD = stdDet;
        
        try {
            LectureQueries lq = new LectureQueries();
            
            ResultSet attList = lq.getAttendanceRecord(stdD.getString("id"));
            
            if(attList!= null){
                if(attList.next()){
                    
                    while(attList.next()){
                        
                        DefaultTableModel model = (DefaultTableModel) tbl_std_dtl_att.getModel();
                        model.setRowCount(0);
                        
                        Object [] row = {attList.getString("subject"),attList.getString("date"),attList.getString("start_time"), attList.getString("end_time"),attList.getString("isAttended")};
                
                        model.addRow(row);
                    }
                    
                }
            }
            
                //System.out.println(stdD.getString("name"));
               lbl_std_dtl_name.setText(stdD.getString("name"));
               lbl_std_dtl_acyr.setText(stdD.getString("ac_yr"));
               lbl_std_dtl_dgr.setText(stdD.getString("degree"));
               lbl_std_dtl_no.setText(stdD.getString("student_no"));
               lbl_std_img.setIcon(resizeImage(stdD.getString("img_path")));
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(StdDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     public ImageIcon resizeImage(String imgPath){
        
        ImageIcon myImage = new ImageIcon(imgPath);
        Image img = myImage.getImage();
        Image newImage = img.getScaledInstance(lbl_std_img.getWidth(), lbl_std_img.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_student_details = new javax.swing.JPanel();
        panel_access_side_bar1 = new javax.swing.JPanel();
        lbl_std_dtl_name = new javax.swing.JLabel();
        lbl_std_dtl_no = new javax.swing.JLabel();
        lbl_std_dtl_acyr = new javax.swing.JLabel();
        lbl_std_dtl_dgr = new javax.swing.JLabel();
        lbl_std_img = new javax.swing.JLabel();
        panel_access_body1 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbl_std_dtl_att = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_student_details.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_access_side_bar1.setBackground(new java.awt.Color(0, 153, 153));

        lbl_std_dtl_name.setBackground(new java.awt.Color(255, 51, 153));
        lbl_std_dtl_name.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_std_dtl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_std_dtl_name.setText("name");

        lbl_std_dtl_no.setBackground(new java.awt.Color(255, 51, 153));
        lbl_std_dtl_no.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_std_dtl_no.setForeground(new java.awt.Color(255, 255, 255));
        lbl_std_dtl_no.setText("no");

        lbl_std_dtl_acyr.setBackground(new java.awt.Color(255, 51, 153));
        lbl_std_dtl_acyr.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_std_dtl_acyr.setForeground(new java.awt.Color(255, 255, 255));
        lbl_std_dtl_acyr.setText("acyr");

        lbl_std_dtl_dgr.setBackground(new java.awt.Color(255, 51, 153));
        lbl_std_dtl_dgr.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_std_dtl_dgr.setForeground(new java.awt.Color(255, 255, 255));
        lbl_std_dtl_dgr.setText("dgr");

        javax.swing.GroupLayout panel_access_side_bar1Layout = new javax.swing.GroupLayout(panel_access_side_bar1);
        panel_access_side_bar1.setLayout(panel_access_side_bar1Layout);
        panel_access_side_bar1Layout.setHorizontalGroup(
            panel_access_side_bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_access_side_bar1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(panel_access_side_bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_std_dtl_name, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(lbl_std_dtl_dgr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_access_side_bar1Layout.createSequentialGroup()
                        .addComponent(lbl_std_dtl_acyr, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_std_img, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(panel_access_side_bar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_std_dtl_no, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_access_side_bar1Layout.setVerticalGroup(
            panel_access_side_bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_access_side_bar1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbl_std_img, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lbl_std_dtl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_std_dtl_no, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_std_dtl_acyr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_std_dtl_dgr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        panel_student_details.add(panel_access_side_bar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, -1));

        panel_access_body1.setBackground(new java.awt.Color(255, 255, 255));
        panel_access_body1.setLayout(new java.awt.CardLayout());

        tbl_std_dtl_att.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_std_dtl_att.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lecture", "Date", "From", "To", "Is Attended?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tbl_std_dtl_att);

        panel_access_body1.add(jScrollPane8, "card2");

        panel_student_details.add(panel_access_body1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 0, 720, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_student_details, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_student_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StdDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StdDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StdDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StdDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new StdDetails().setVisible(true);
                new IMAccess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lbl_std_dtl_acyr;
    private javax.swing.JLabel lbl_std_dtl_dgr;
    private javax.swing.JLabel lbl_std_dtl_name;
    private javax.swing.JLabel lbl_std_dtl_no;
    private javax.swing.JLabel lbl_std_img;
    private javax.swing.JPanel panel_access_body1;
    private javax.swing.JPanel panel_access_side_bar1;
    private javax.swing.JPanel panel_student_details;
    private javax.swing.JTable tbl_std_dtl_att;
    // End of variables declaration//GEN-END:variables
}
