/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imaccess;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ACER
 */
public class StdDetails extends javax.swing.JFrame {

    /**
     * Creates new form StdDetails
     */
    public StdDetails(ResultSet stdDet) {
        initComponents();
        
        ResultSet stdD = stdDet;
        
        try {
            
            
                //System.out.println(stdD.getString("name"));
               lbl_std_dtl_name.setText(stdD.getString("name"));
               lbl_std_dtl_acyr.setText(stdD.getString("ac_yr"));
               lbl_std_dtl_dgr.setText(stdD.getString("degree"));
               lbl_std_dtl_no.setText(stdD.getString("student_no"));
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(StdDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_student_details = new javax.swing.JPanel();
        panel_access_side_bar1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbl_std_dtl_name = new javax.swing.JLabel();
        lbl_std_dtl_no = new javax.swing.JLabel();
        lbl_std_dtl_acyr = new javax.swing.JLabel();
        lbl_std_dtl_dgr = new javax.swing.JLabel();
        lbl_std_dtl_acyr2 = new javax.swing.JLabel();
        panel_access_body1 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbl_std_dtl_att = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_student_details.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_access_side_bar1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        lbl_std_dtl_name.setBackground(new java.awt.Color(255, 51, 153));
        lbl_std_dtl_name.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_std_dtl_name.setForeground(new java.awt.Color(255, 255, 255));

        lbl_std_dtl_no.setBackground(new java.awt.Color(255, 51, 153));
        lbl_std_dtl_no.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_std_dtl_no.setForeground(new java.awt.Color(255, 255, 255));

        lbl_std_dtl_acyr.setBackground(new java.awt.Color(255, 51, 153));
        lbl_std_dtl_acyr.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_std_dtl_acyr.setForeground(new java.awt.Color(255, 255, 255));

        lbl_std_dtl_dgr.setBackground(new java.awt.Color(255, 51, 153));
        lbl_std_dtl_dgr.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_std_dtl_dgr.setForeground(new java.awt.Color(255, 255, 255));

        lbl_std_dtl_acyr2.setBackground(new java.awt.Color(255, 51, 153));
        lbl_std_dtl_acyr2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_std_dtl_acyr2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_access_side_bar1Layout = new javax.swing.GroupLayout(panel_access_side_bar1);
        panel_access_side_bar1.setLayout(panel_access_side_bar1Layout);
        panel_access_side_bar1Layout.setHorizontalGroup(
            panel_access_side_bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_access_side_bar1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_access_side_bar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_std_dtl_no, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_access_side_bar1Layout.createSequentialGroup()
                .addGroup(panel_access_side_bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_access_side_bar1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbl_std_dtl_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_access_side_bar1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_access_side_bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_std_dtl_dgr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_access_side_bar1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbl_std_dtl_acyr, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_access_side_bar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_std_dtl_acyr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_access_side_bar1Layout.setVerticalGroup(
            panel_access_side_bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_access_side_bar1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_std_dtl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_std_dtl_no, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_std_dtl_acyr2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lbl_std_dtl_acyr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_std_dtl_dgr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        panel_student_details.add(panel_access_side_bar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, -1));

        panel_access_body1.setBackground(new java.awt.Color(255, 255, 255));
        panel_access_body1.setLayout(new java.awt.CardLayout());

        tbl_std_dtl_att.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_std_dtl_att.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lecture", "Date", "From", "To", "Is Attended?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tbl_std_dtl_att);

        panel_access_body1.add(jScrollPane8, "card2");

        panel_student_details.add(panel_access_body1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 0, 720, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_student_details, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_student_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StdDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StdDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StdDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StdDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new StdDetails().setVisible(true);
                new IMAccess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lbl_std_dtl_acyr;
    private javax.swing.JLabel lbl_std_dtl_acyr2;
    private javax.swing.JLabel lbl_std_dtl_dgr;
    private javax.swing.JLabel lbl_std_dtl_name;
    private javax.swing.JLabel lbl_std_dtl_no;
    private javax.swing.JPanel panel_access_body1;
    private javax.swing.JPanel panel_access_side_bar1;
    private javax.swing.JPanel panel_student_details;
    private javax.swing.JTable tbl_std_dtl_att;
    // End of variables declaration//GEN-END:variables
}
